[theme]
base="dark"

primaryColor="#ebebecff"
backgroundColor="#000000ff"
secondaryBackgroundColor="#1b1135ff"
borderColor="#836fc1ff"

textColor="#edeffeff"
font="Nunito:https://fonts.googleapis.com/css2?family=Nunito&display=swap"

showWidgetBorder = true


[server]
headless = true
runOnSave = true
fileWatcherType = "poll"
